-- Copyright (C) 1991-2013 Altera Corporation
-- Your use of Altera Corporation's design tools, logic functions 
-- and other software and tools, and its AMPP partner logic 
-- functions, and any output files from any of the foregoing 
-- (including device programming or simulation files), and any 
-- associated documentation or information are expressly subject 
-- to the terms and conditions of the Altera Program License 
-- Subscription Agreement, Altera MegaCore Function License 
-- Agreement, or other applicable license agreement, including, 
-- without limitation, that your use is for the sole purpose of 
-- programming logic devices manufactured by Altera and sold by 
-- Altera or its authorized distributors.  Please refer to the 
-- applicable agreement for further details.

-- Generated by Quartus II Version 13.0.1 Build 232 06/12/2013 Service Pack 1 SJ Web Edition
-- Created on Wed Nov 06 12:57:48 2024

LIBRARY ieee;
USE ieee.std_logic_1164.all;

ENTITY esclavo IS
    PORT (
        reset : IN STD_LOGIC := '0';
        clock : IN STD_LOGIC;
        SDA : IN STD_LOGIC := '0';
        fin_dir : IN STD_LOGIC := '0';
        fin_dato : IN STD_LOGIC := '0';
        soy : IN STD_LOGIC := '0';
        hab_dato : OUT STD_LOGIC;
        hab_dir : OUT STD_LOGIC;
        hab_ACK : OUT STD_LOGIC
    );
END esclavo;

ARCHITECTURE BEHAVIOR OF esclavo IS
    TYPE type_fstate IS (OSCIOSO,START,guarda_dir,RW,ACK,guardadato);
    SIGNAL fstate : type_fstate;
    SIGNAL reg_fstate : type_fstate;
BEGIN
    PROCESS (clock,reg_fstate)
    BEGIN
        IF (clock='1' AND clock'event) THEN
            fstate <= reg_fstate;
        END IF;
    END PROCESS;

    PROCESS (fstate,reset,SDA,fin_dir,fin_dato,soy)
    BEGIN
        IF (reset='1') THEN
            reg_fstate <= OSCIOSO;
            hab_dato <= '0';
            hab_dir <= '0';
            hab_ACK <= '0';
        ELSE
            hab_dato <= '0';
            hab_dir <= '0';
            hab_ACK <= '0';
            CASE fstate IS
                WHEN OSCIOSO =>
                    IF ((SDA = '0')) THEN
                        reg_fstate <= START;
                    ELSIF ((SDA = '1')) THEN
                        reg_fstate <= OSCIOSO;
                    -- Inserting 'else' block to prevent latch inference
                    ELSE
                        reg_fstate <= OSCIOSO;
                    END IF;

                    hab_ACK <= '0';

                    hab_dir <= '0';

                    hab_dato <= '0';
                WHEN START =>
                    reg_fstate <= guarda_dir;

                    hab_ACK <= '0';

                    hab_dir <= '0';

                    hab_dato <= '0';
                WHEN guarda_dir =>
                    IF ((fin_dir = '0')) THEN
                        reg_fstate <= guarda_dir;
                    ELSIF (((fin_dir = '1') AND (soy = '1'))) THEN
                        reg_fstate <= RW;
                    ELSIF (((fin_dir = '1') AND (soy = '0'))) THEN
                        reg_fstate <= OSCIOSO;
                    -- Inserting 'else' block to prevent latch inference
                    ELSE
                        reg_fstate <= guarda_dir;
                    END IF;

                    hab_ACK <= '0';

                    hab_dir <= '1';

                    hab_dato <= '0';
                WHEN RW =>
                    reg_fstate <= ACK;

                    hab_ACK <= '0';

                    hab_dir <= '0';

                    hab_dato <= '0';
                WHEN ACK =>
                    reg_fstate <= guardadato;

                    hab_ACK <= '1';

                    hab_dir <= '0';

                    hab_dato <= '0';
                WHEN guardadato =>
                    IF ((fin_dato = '0')) THEN
                        reg_fstate <= guardadato;
                    ELSIF ((fin_dato = '1')) THEN
                        reg_fstate <= OSCIOSO;
                    -- Inserting 'else' block to prevent latch inference
                    ELSE
                        reg_fstate <= guardadato;
                    END IF;

                    hab_ACK <= '0';

                    hab_dir <= '0';

                    hab_dato <= '1';
                WHEN OTHERS => 
                    hab_dato <= 'X';
                    hab_dir <= 'X';
                    hab_ACK <= 'X';
                    report "Reach undefined state";
            END CASE;
        END IF;
    END PROCESS;
END BEHAVIOR;
